# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


stages:
- stage: Build
  displayName: 'Building the react app'
  jobs:
  - job:
    displayName: 'Job to build the app'
    pool:
      name: Release

    steps:
    - script: | 
         npx create-react-app my-app --use-npm
         ls
         cp -r my-app $(Build.ArtifactStagingDirectory)

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'my-app'  # Specify a unique artifact name
        displayName: 'Publish my-app artifact'
        
- stage: Release
  displayName: 'release the react app'
  jobs:
  - job:
    displayName: 'Pubish the app'
    pool:
      name: Release
      
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          artifactName: 'my-app'  # Specify the same artifact name used in the TrivyScan stage
          path: $(Build.ArtifactStagingDirectory)
        displayName: 'Download my-app artifact'
        
      - script: |
          chmod 755 $(Build.ArtifactStagingDirectory)/my-app
          cd $(Build.ArtifactStagingDirectory)/my-app
          npm run start
